### PR TITLE
cachequeryqueue.py: support querying sources when artifacts are cached

### LINKED ISSUE #1749: BUG when using the `storage-service` cache option
After adding the `storage-service` cache option, I get the following error. The cache wasn't completely empty (was used as an artifact cache and source cache before) but isn't completely up to date either.

It seems it is trying to push sources for an element without first querying the cache to check that the source is cached.

```
[05:36:29][--:--:--][        ][    main:core activity                 ] BUG     
    Traceback (most recent call last):
      File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/scheduler.py", line 438, in real_schedule
        self._sched_queue_jobs()
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/scheduler.py", line 378, in _sched_queue_jobs
        queue.enqueue(elements)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/queues/queue.py", line 192, in enqueue
        self._enqueue_element(elt)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/queues/queue.py", line 385, in _enqueue_element
        status = self.status(element)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/queues/sourcepushqueue.py", line 36, in status
        if element._skip_source_push():
      File "/usr/lib/python3.10/site-packages/buildstream/element.py", line 1917, in _skip_source_push
        return not (self.__sourcecache.has_push_remotes(plugin=self) and self._cached_sources())
      File "/usr/lib/python3.10/site-packages/buildstream/element.py", line 2279, in _cached_sources
        return self.__sources.cached()
      File "/usr/lib/python3.10/site-packages/buildstream/_elementsources.py", line 342, in cached
        assert self._cached is not None
    AssertionError
```

### PR DESCRIPTION
**Pull request by abderrahim**
Fixes #1749

### CODE REVIEW

**Comment by juergbi** [comment]
The changes to match the serial cache query logic make sense to me. A test case would be good but I don't know how tricky this is to add. Build with `storage-service` and source push enabled with a target that is already built and cached?

**Comment by nanonyme** [comment]
This seems to fix the immediate problem based on our testing integration testing in freedesktop-sdk.

**Comment by jjardon** [comment]
@abderrahim can we remove the Draft status from this or something else is still needed?

**Comment by abderrahim** [comment]
I've removed the draft status. I think it's ready, but I'm not sure how to test it.

Maybe we should simply make this the default path, and find a way to simplify the output (as it's currently very verbose).

**Comment by nanonyme** [comment]
@juergbi note we have done end-to-end testing a lot with this in freedesktop-sdk and it seems to fix the problems. Using storage service works reliably with this change.

**Review by juergbi — APPROVED** [review]

**Pull request merged**
