### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by jjardon**
Following the steps documented here:
doc/source/hacking/updating_python_deps.rst

### CODE REVIEW

**Comment by nanonyme** [comment]
Are you sure this actually adds testing for Python 3.12? It requires Python 39 afaik.

**Comment by nanonyme** [comment]
Fedora 39 is now out so it can be added to CI

**Comment by nanonyme** [comment]
@jjardon  @abderrahim this should now be closed

**Comment by abderrahim** [comment]
Merged as part of https://github.com/apache/buildstream/pull/1881

**Pull request closed without merging**
