### PR TITLE
Update pylint config and fix some trivial issues

### PR DESCRIPTION
**Pull request by ghost**
This enables `lint` test to pass with Pylint >= 2.14.

### CODE REVIEW

**Comment by ghost** [comment]
Seems this cannot work as-is with Pylint 2.13, as the `no-self-use` checks needs to be disabled there.

**Comment by gtristan** [comment]
> Seems this cannot work as-is with Pylint 2.13, as the `no-self-use` checks needs to be disabled there.

Better not try to submit this change separately to the branch which updates the requirements.

**Comment by ghost** [comment]
Yes, can merge into https://github.com/apache/buildstream/pull/1714 if that's acceptable

**Comment by gtristan** [comment]
> Yes, can merge into #1714 if that's acceptable

Of course

**Pull request closed without merging**
