### PR TITLE
_platform: add LoongArch to the list of supported platforms

### PR DESCRIPTION
**Pull request by cheese**
See https://github.com/bazelbuild/remote-apis/pull/237

Part of https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1534

### CODE REVIEW

**Review by cs-shadow — APPROVED** [review]

**Comment by nanonyme** [comment]
This is again absolutely not going to move forward unless either @cheese signs Google CLA or someone who has signed Google CLA submits the work. I did some prodding and seems while there is positively at least some discussion whether CLA makes sense for said documentation repo, Google is unlikely to budge at all.

**Comment by cheese** [comment]
I have signed Google CLA.

**Comment by gtristan** [comment]
Looking at the fdsdk issue, I think it is prudent to wait for the next release and for these patches to land in the other upstream BuildStream dependencies and google APIs first.

**Comment by nanonyme** [comment]
I would noted that the remote apis PR went through. Maybe it's time to land this or do you prefer https://gitlab.com/BuildGrid/buildbox/buildbox-common/-/merge_requests/486 still lands in a release?

**Review by juergbi — APPROVED** [review]

**Pull request merged**
