### PR TITLE
Fix `MappingNode._composite()`

### PR DESCRIPTION
**Pull request by gtristan**
This branch fixes `Node._composite()` so that mutable data in the *source* nodes are no longer given away to the composite *target*, leaving the *source* vulnerable to later mutations when the *target* is mutated. Instead clones of source values are provided when they are composited onto a target node.

### CODE REVIEW

**Review by BenjaminSchubert — APPROVED** [review]

**Comment by nanonyme** [comment]
Is this really sufficient case to trigger the bug? Don't you need to have multiple elements, some of which are not parallel and some which are? I think @abderrahim was at least saying the issue is some variable is pre-expanded that shouldn't be.

**Comment by gtristan** [comment]
> Is this really sufficient case to trigger the bug? Don't you need to have multiple elements, some of which are not parallel and some which are? I think @abderrahim was at least saying the issue is some variable is pre-expanded that shouldn't be.

Not yet, no.

**Comment by gtristan** [comment]
> > Is this really sufficient case to trigger the bug? Don't you need to have multiple elements, some of which are not parallel and some which are? I think @abderrahim was at least saying the issue is some variable is pre-expanded that shouldn't be.
> 
> Not yet, no.

This has now been updated to properly trigger the bug.

**Comment by gtristan** [comment]
And this merge request has now been updated to include both the test case and the fix for the underlying composition issue.

@BenjaminSchubert, can you take a look at this ?

**Review by BenjaminSchubert — APPROVED** [review]

**Comment by gtristan** [comment]
We’ve got some kind of github bug, the CI actions appear to be randomly getting cancelled :(

**Pull request merged**
