### PR TITLE
Add release notes for bst 1.6.8

### PR DESCRIPTION
**Pull request by nanonyme**

### CODE REVIEW

**Comment by nanonyme** [comment]
Ping @jjardon

**Comment by abderrahim** [comment]
I'd like to backport https://github.com/apache/buildstream/pull/1436 too before the next release.

**Comment by nanonyme** [comment]
Fair. We can pull that in. We IMHO need the new release asap though far this Fall Fedora release

**Comment by nanonyme** [comment]
@abderrahim rebased and mentioned your change in release notes.

**Comment by abderrahim** [comment]
Maybe add the python 3.11 fix if it works now? (or maybe we still need to change the requirements?)

**Comment by nanonyme** [comment]
I don't think there's much we can do at the moment to fix Python 3.11 for pip installs. Someone needs to file a bug against ruamel.yaml.clib.

**Comment by nanonyme** [comment]
But this allows fixing the Fedora-shipped version of bst which is nice.

**Comment by nanonyme** [comment]
I can add comment about the backport, sure.

**Comment by nanonyme** [comment]
Done.

**Comment by nanonyme** [comment]
I would prefer not going as far as claiming Python 3.11 support is fixed though it probably is.

**Pull request merged**
