### PR TITLE
bst1: Support Python 3.11

### PR DESCRIPTION
**Pull request by nanonyme**
Fixes https://github.com/apache/buildstream/issues/1758

### CODE REVIEW

**Comment by mcatanzaro** [comment]
Why is this still a draft?

**Comment by nanonyme** [comment]
@mcatanzaro tests don't pass and it's not directly related to Python 3.11

**Comment by nanonyme** [comment]
I am not getting a pipeline, dunno why.

**Comment by nanonyme** [comment]
I'm not entirely sure if tests hang on Fedora  36 and 37 but at least they're massively slower.

**Comment by nanonyme** [comment]
Looks like there are failing tests. The failing tests are failing really slowly. I'm trying to make tests abort after first failure so we see real output.

**Comment by nanonyme** [comment]
Well, that was not overly useful. I got it to actually end and we're maybe a bit closer to understanding why the test is so slow https://github.com/apache/buildstream/actions/runs/3688689726/jobs/6243779599 but the traceback is mostly gibberish and there is no console output

**Comment by mcatanzaro** [comment]
Hi @gtristan, can you look at this please? buildstream 1 is really super broken currently, and for a very long time now (it's not like python 3.11 is new anymore).

**Comment by nanonyme** [comment]
Note that this is about CI and testing on Python 3.11. This has no functional changes.

**Comment by mcatanzaro** [comment]
Oops, I see it is #1758 that requires attention, not this #1785.

**Comment by nanonyme** [comment]
There are unreleased fixes for Python3.11 in bst-1 branch. But without CI it's hard to say whether further things are broken.

**Comment by mcatanzaro** [comment]
Er, why not release them then? This has been blocking a lot of stuff for a long time.

(I agree that CI is very important, but it's not urgent.)

**Comment by nanonyme** [comment]
It would be nice if someone pip installed bst1 from this repo who actually has Python3.11 to give it at least some lightweight manual testing.

**Comment by jjardon** [comment]
@mcatanzaro @nanonyme I _think_ that is what is being done in #1757 (It hangs forever)

**Comment by nanonyme** [comment]
@jjardon I am not taking about CI. Just install it and use it. It will not hang. See if there are further regressions.

**Comment by nanonyme** [comment]
If it seems usable, then we tag a release and worry about CI later.

**Comment by nanonyme** [comment]
The hangs are related to special way bst event loop is used  for unittest purposes in same process restarting it over and over again. They are not indicative of real problems.

**Comment by nanonyme** [comment]
@jjardon it also does not hang "forever". Asyncio gets into bad state and times out with 30 minutes at a time. It just times out dozens of times in a loop so it looks like forever.

**Comment by mcatanzaro** [comment]
> It would be nice if someone pip installed bst1 from this repo who actually has Python3.11 to give it at least some lightweight manual testing.

You don't have access to an F37 toolbx container? That should take maybe two minutes to create. Whatever. I installed this branch and am building gnome-build-meta with it now. Will let you know how it goes....

**Comment by mcatanzaro** [comment]
> Will let you know how it goes....

Well it finished successfully, but I think it pulled everything from the artifact cache without actually building anything.

Want me to test anything else in particular?

**Comment by nanonyme** [comment]
I think that's strong indication we should wrap a quick release. If you can build something (doesn't matter what, you can force rebuild by setting environment variable in some element), that would be even better.

**Comment by nanonyme** [comment]
I created https://github.com/apache/buildstream/pull/1809 anyhow. I would like to have CI actually work before advertising Python 3.11 support in metadata. But this should hopefully unblock downstreams.

**Comment by mcatanzaro** [comment]
> I think that's strong indication we should wrap a quick release. If you can build something (doesn't matter what, you can force rebuild by setting environment variable in some element), that would be even better.

Did this to force building core/epiphany.bst. It worked.

**Comment by gtristan** [comment]
This is replaced by #1827

**Pull request closed without merging**
