### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by ghost**
Following the steps documented here:
https://github.com/apache/buildstream/pull/1738/

### CODE REVIEW

**Comment by ghost** [comment]
Local testing with `tox -e py311-nocover` fails due to <strike>ruamel.yaml</strike> pyroaring failing to `pip install` with CPython 3.11: see discussion in https://github.com/apache/buildstream/issues/1758

**Comment by ghost** [comment]
Pyroaring 0.34 is available since 2022-11-09 which seems to support Python 3.11.

This is now ready apart from some test failures in the fedora-36 test job, apparently involving `buildbox-casd`.

**Comment by ghost** [comment]
On retry the tests all pass.

**Comment by nanonyme** [comment]
Good stuff. It would be nice to include this and roll release soon after so we get manywheels published.

**Review by abderrahim — APPROVED** [review]

**Pull request merged**
