### PR TITLE
requirements: Limit grpcio to >= 1.34 and < 1.39

### PR DESCRIPTION
**Pull request by gtristan**
We are experiencing segfaults with grpcio > 1.39, consistently with
python3.9 and spuriously with other versions of python too.

### CODE REVIEW

**Comment by gtristan** [comment]
I've narrowed it down to which versions are broken, seems to be `grpcio >= 1.39`

This last test should be checking `1.38.1` https://gitlab.com/BuildStream/buildstream-docker-images/-/jobs/1728633087 which is the latest pre 1.39 version (lets wait for it to be successful, so far I've only tested up to 1.38.0 but I suspect it will be the same as 1.38.1)

**Comment by gtristan** [comment]
oh crap, more linter changes...

**Comment by nanonyme** [comment]
Interesting. bst1 works just fine with grpcio 1.39.1 which is now in Fedora 35. Looks like buildstream-docker-images is out of date and running on old version of Fedora.

**Comment by juergbi** [comment]
> Interesting. bst1 works just fine with grpcio 1.39.1 which is now in Fedora 35. Looks like buildstream-docker-images is out of date and running on old version of Fedora.

The bst2 test suite crashes even on Fedora 35 with grpcio 1.39 installed by tox: https://gitlab.com/BuildStream/buildstream-docker-images/-/jobs/1732134224

**Comment by nanonyme** [comment]
I don't trust grpcio installed with tox much. Is it possible to test with distro grpcio in F35? We made sure it has new enough and working grpcio since it's the most typical production platform for BuildStream (due to gnome-build-meta project)

**Comment by gtristan** [comment]
> I don't trust grpcio installed with tox much. Is it possible to test with distro grpcio in F35? We made sure it has new enough and working grpcio since it's the most typical production platform for BuildStream (due to gnome-build-meta project)

Well, the point is to test with all of the major versions that are not EOL, according to https://fedoraproject.org/wiki/End_of_life it seems that 33 and 34 are not EOL yet (Note that this branch itself has commented out most of the CI in order to test this patch more efficiently). The point of course being to run CI in the buildstream repo for many different active distro versions.

We can of course *add* F35 but this doesn't fix breakage on existing supported platforms.

**Comment by gtristan** [comment]
> > Interesting. bst1 works just fine with grpcio 1.39.1 which is now in Fedora 35. Looks like buildstream-docker-images is out of date and running on old version of Fedora.
> 
> The bst2 test suite crashes even on Fedora 35 with grpcio 1.39 installed by tox: https://gitlab.com/BuildStream/buildstream-docker-images/-/jobs/1732134224

So, to clarify, the newer python from F35 combined with grpcio 1.39 breaks equally.

I think it's fairly safe to deduce that this is a grpcio issue that is triggered with newer versions of python (and that bst2 exercises grpcio in it's tests a lot more than bst1 does, exposing this issue).

At this point we've found a range of grpcio versions which works, if we had more info on this we could report it upstream to grpcio and hope for a fix in a future `> 1.41.1` version.

**Pull request merged**
