### PR TITLE
Override project defined source mirrors, and be selective about what mirrors to use

### LINKED ISSUE #1484: Override aliases and mirrors in junctioned projects
This would be an essential feature to allow projects to store all the source code in their own mirrors, it is important for the parent/main project to store all of the source code and ensure that it can be built in perpetuity.

### PR DESCRIPTION
**Pull request by gtristan**
This fixes #1484, and implements the [proposal](https://lists.apache.org/api/source.lua?id=1w3s72q4yf23rx0yc57tw0lf94q3g5bj)

### CODE REVIEW

**Comment by jjardon** [comment]
@gtristan Would it be possible to backport this to bst-1? We need this feature to use our own mirrors in GNOME

**Comment by gtristan** [comment]
This branch has been updated to provide full test coverage.

**Comment by gtristan** [comment]
> @gtristan Would it be possible to backport this to bst-1? We need this feature to use our own mirrors in GNOME

It seems that this would be technically possible yes. It would be a bit more fragile in `bst-1` due to project name uniqueness not being strictly enforced (mostly the addressing scheme works only with junction names, although we already have the `projects` user configuration section in `bst-1`) - although in practice this would not realistically cause issues.

**Comment by gtristan** [comment]
This actually passes it's tests, however is failing in CI due to #1368 (well known spurious failure) and now #1549 which is causing all our workflows to fail.

**Comment by gtristan** [comment]
As it was questioned in #1542, should we:

* Remove the strange behavior of traversing active mirrors/URLs backwards when tracking ?
* Make the default track source policy be to ignore mirrors and track only from the originally defined aliases ?
  * This would IMO address the concern that we *want* to track upstream by default even though we want to *fetch* from our own mirrors, in order to ensure we get new refs from upstream even when our downstream mirroring solutions might be lagging behind or broken

**Comment by jjardon** [comment]
> As it was questioned in #1542, should we:
> 
>     * Remove the strange behavior of traversing active mirrors/URLs backwards when tracking ?
> 
>     * Make the default track source policy be to ignore mirrors and track only from the originally defined aliases ?
>       
>       * This would IMO address the concern that we _want_ to track upstream by default even though we want to _fetch_ from our own mirrors, in order to ensure we get new refs from upstream even when our downstream mirroring solutions might be lagging behind or broken

I can see we want to get upstream to get the latest, but then we have another problem if we use a tag that is not in our mirror as next build fetch will fail (if we restrict your project to only use mirrors, for example)

So, I think default should be always be (for both track and fetch):
- 1. Try to use mirror
- 2. Try to use upstream

but that order should be configurable separately for track and fetch, so you can select the behaviour you want for your project

**Review by BenjaminSchubert — APPROVED** [review]
I did not do a thorough review, but tests and documentation seem good.

**Comment by gtristan** [comment]
> 
> I can see we want to get upstream to get the latest,

Right, that is the rationale behind the original special case to reverse the URLs when tracking - which is fairly obsolete by this branch.

> but then we have another problem if we use a tag that is not in our mirror as next build fetch will fail (if we restrict your project to only use mirrors, for example)

Which I think is desirable, we want to have an error as early as possible when our mirrors are not working right ?

> So, I think default should be always be (for both track and fetch):
> 
>     * 1. Try to use mirror
> 
>     * 2. Try to use upstream

Agree for `fetch`, disagree for `track`, I think by default tracking should *only* track upstreams.

Other than that, I don't think that an order is very necessary.

It's important to note that once a remote is *reached* and successfully tracked, then we will *not* rollover to the next mirror to see if we get anything more recent (and there is no concept of "recent", only what happens to be at the tip of a tracking branch).

This is to say that if you track your mirror first and successfully reach it, and it does **not** have the latest upstream yet (because the mirror is not mirroring correctly), then we would silently ignore the upstream.

> but that order should be configurable separately for track and fetch, so you can select the behaviour you want for your project

I'm skeptical about retaining configurability of the reverse order - with the current approach the user can dictate an order of mirrors to use in `buildstream.conf` anyway, by way of explicitly overriding project declared mirrors, but I doubt that is useful in practice.

**Comment by gtristan** [comment]
Updated branch so that:
* We remove the obsolete hard code which reverses URIs when tracking
* Make the default track policy "aliases", so that (by default) we track only from original upstreams instead of mirrors which could be out of date

**Comment by juergbi** [comment]
> Updated branch so that:
> 
>     * We remove the obsolete hard code which reverses URIs when tracking
> 
>     * Make the default track policy "aliases", so that (by default) we track only from original upstreams instead of mirrors which could be out of date

This seems reasonable to me and the branch looks good to me - once the failing tests have been fixed.

It might be possible to reduce the load on upstream/alias servers (at least for git) if we fetch from a mirror before we fetch from upstream for actual tracking. That way BuildStream would download very little from upstream, unless the mirror is out-of-date, without any risk of getting stale or wrong information from a mirror when tracking. However, I don't know whether this would be an important optimization. I certainly don't consider this a blocker for this PR.

**Comment by gtristan** [comment]
> It might be possible to reduce the load on upstream/alias servers (at least for git) if we fetch from a mirror before we fetch from upstream for actual tracking. That way BuildStream would download very little from upstream, unless the mirror is out-of-date, without any risk of getting stale or wrong information from a mirror when tracking. However, I don't know whether this would be an important optimization. I certainly don't consider this a blocker for this PR.

That is the current (unchanged) behavior. The reversal which I removed was a special case for running `bst track` only, this PR doesn't change the default behavior when all URI sources are allowed, which is to place mirrors before the default upstream.

**Pull request merged**
