### PR TITLE
Update CI images for new Fedora versions

### PR DESCRIPTION
**Pull request by ghost**
Fedora 38 is released, and Fedora 36 is end-of-life.

See also: https://gitlab.com/BuildStream/buildstream-docker-images/-/merge_requests/218

### CODE REVIEW

**Review by cs-shadow — APPROVED** [review]

**Comment by cs-shadow** [comment]
hmm not sure what's going on with the github runners, all the test jobs seem to get stuck with:

> ﻿﻿Waiting for a runner to pick up this job... 

and then seem to timeout

**Comment by abderrahim** [comment]
I'm pretty sure the problem is that there is no longer any `ubuntu-18.04` runner hosted by github.

**Comment by ghost** [comment]
> I'm pretty sure the problem is that there is no longer any `ubuntu-18.04` runner hosted by github.

OK, if thats the issue i can update the PR :)

**Comment by ghost** [comment]
It seems that every change I make to the CI config requires a maintainer to re-approve the PR, which makes it almost impossible for me to iterate on this PR usefully.

image

**Comment by cs-shadow** [comment]
I'm sorry about the approval policy, but i also don't think we have too much control over it. It's something set by the Apache team globally. The announcement around this did mention some resources that we can try reaching out to see if we can get some exceptions. I'll give that a go but not holding my breath for it.

**Comment by cs-shadow** [comment]
Thanks for fixing this though!

**Pull request merged**
