### PR TITLE
Stop using child process for downloading URL's

### PR DESCRIPTION
**Pull request by nanonyme**
Related to https://github.com/apache/buildstream/issues/1766 and https://github.com/apache/buildstream/issues/1761 This makes things really hard to debug when there are errors and downloading is mostly done with GIL dropped.

### CODE REVIEW

**Comment by abderrahim** [comment]
It just crossed my mind that maybe what was meant by "starving the scheduler" isn't actually about the GIL. Can you please try to terminate a fetch during download and see if it works?

**Comment by nanonyme** [comment]
Good point. Though I don't think termination works right now either. You get a really miserable set of stacktraces which eventually maybe results in stopping.

**Comment by nanonyme** [comment]
I converted this into draft so won't be accidentally merged before the important question is answered.

**Comment by nanonyme** [comment]
@abderrahim has better fix for this at https://github.com/apache/buildstream/pull/1814

**Pull request closed without merging**
