### PR TITLE
Implement new --retry-failed behavior

### PR DESCRIPTION
**Pull request by gtristan**
This addresses #1335

### CODE REVIEW

**Comment by nanonyme** [comment]
Does this work as user config? That's a requirement for the feature.

**Comment by gtristan** [comment]
> Does this work as user config? That's a requirement for the feature.

Yes, and the patch updates the user config documentation accordingly.

**Comment by nanonyme** [comment]
Looks good to me then.

**Review by cs-shadow — APPROVED** [review]
Looks good to me, thanks!

**Review by juergbi — APPROVED** [review]

**Comment by doraskayo** [comment]
Thanks for working on this, @gtristan. I hope to see it merged soon.

In the meantime, we're going to backport this MR to our CI images. This limitation is (again) blocking us from making a release due to a cached failure (OOM).

See: https://gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images/-/merge_requests/426

**Comment by gtristan** [comment]
> Thanks for working on this, @gtristan. I hope to see it merged soon.
> 
> In the meantime, we're going to backport this MR to our CI images. This limitation is (again) blocking us from making a release due to a cached failure (OOM).
> 
> See: https://gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images/-/merge_requests/426

Hi @doraskayo,

Sure, just FYI, the only reason I didn't merge it quite yet is that it adds a feature, and in 2.x we have not really ironed out policy about branching around stable versions, and also want to change the version numbering in 2.x to meet normal expectations around semver: https://lists.apache.org/thread/yxl6438r3wq2655v1ot8z909t01ccr6k

I expect to release this in a 2.1.0 release but just need to iron out some kinks to make that possible.

**Comment by nanonyme** [comment]
I suggest calling it 2.0.2 to maximize probability all distros consider it a bug fix release and pull it in. BuildStream is not usable without this as was known before 2.0.0.

**Comment by nanonyme** [comment]
This was somewhat erroneously not flagged as blocking 2.0.0.

**Comment by nanonyme** [comment]
If you intend this change to go in as unstable release, bear in mind downstreams are going to ignore your versioning.

**Comment by gtristan** [comment]
> I suggest calling it 2.0.2 to maximize probability all distros consider it a bug fix release and pull it in. BuildStream is not usable without this as was known before 2.0.0.

This is not a patch release as it adds a feature/API.

> This was somewhat erroneously not flagged as blocking 2.0.0.

I don't believe this was an error, it's inconvenient but recoverable either by zapping the cache, or by running `bst artifact delete` and running the build again while disabling remote cache access (doable on the CLI by specifying an invalid artifact remote).

Inconveniences such as these, which are recoverable, was explicitly discussed in 2.0 team meetings - we needed to set the bar low enough for 2.0 to be achievable.

> If you intend this change to go in as unstable release, bear in mind downstreams are going to ignore your versioning.

I don't think this feature addition warrants an unstable cycle, it's not a very complicated or experimental change.

We intend to release this as a stable feature release: 2.1.0

As I cited in https://lists.apache.org/thread/yxl6438r3wq2655v1ot8z909t01ccr6k, we just want to fix some mechanics to allow us to break free of the non-standard _"odd number minor point means unstable"_ convention which we originally inherited from the GNOME project (and is not really a semantic used anywhere else, and is generally confusing except to GNOME developers).

**Comment by nanonyme** [comment]
The things your are proposing are usually limited to very few people in any largers BuildStream projects. Access to cache has huge security impact.

**Comment by nanonyme** [comment]
Ok. It wasn't obvious from thread what the final versioning scheme was. It sounded like you were still operating on odd/even. Sorry for overreacting if this goes into stable releases around September.

**Pull request merged**
