### PR TITLE
requirements.txt: Bump grpc version to be compatible with Python 3.11

### PR DESCRIPTION
**Pull request by cs-shadow**
missed this in #1806

### CODE REVIEW

**Comment by cs-shadow** [comment]
seems like our testsuite is busted with the new version of grpc, draft for now

**Comment by nanonyme** [comment]
Yeah, there's similarly issues with bst1. In there it looked there was some general timeout in asyncio reactor getting hit with timeout of 30 minutes *per test*.

**Comment by nanonyme** [comment]
As per one of the CI runs that actually *exited*, it looks like there's leftover grpcio threads from tests. We're not running bst like normal (launch bst as a subprocess) but instead running bst main function inside pytest. This leaks grpcio into pytest test runner which can result in all kinds of trouble if it doesn't properly terminate. (but which real users of BuildStream can never encounter) I tried refactoring earlier the setup to instead call bst through subprocess but it turned out we have some exception analysis in tests that is impossible to do if you aren't in same process as bst.

**Comment by juergbi** [comment]
Replaced by #1815, which fixes the tests.

**Pull request closed without merging**
