### PR TITLE
tox.ini: add --namespace-packages to mypy

### PR DESCRIPTION
**Pull request by abderrahim**
It is needed by latest version of types-protobuf

Also update mypy to the latest version

### CODE REVIEW

**Comment by juergbi** [comment]
The change in types-protobuf was reverted: https://github.com/python/typeshed/pull/7522
mypy should work again with 3.19.15 even without `--namespace-packages`.

I don't know whether it still makes sense to add this option.

**Comment by abderrahim** [comment]
> I don't know whether it still makes sense to add this option.
The issue mentioned that it would be the default in the next version of mypy.

What we could do instead is to depend on `types-protobuf != 3.19.14`, this way it should fix the current issue and keep working when 3.19.15 is released.

**Comment by juergbi** [comment]
types-protobuf 3.19.15 has already been released on PyPI.

**Comment by juergbi** [comment]
This was added as part of #1782.

**Pull request closed without merging**
