### PR TITLE
Heal from corruption where cache_size is empty file

### LINKED ISSUE #1540: [bst-1] "Error instantiating artifact cache: Size '' parsed from '/home/fedora/.cache/buildstream/artifacts/cache_size' was not an integer"
I had to shut down server while it was in the middle of running a bst (1.6.3) command. On restart, bst fails with

"Error instantiating artifact cache: Size '' parsed from '/home/fedora/.cache/buildstream/artifacts/cache_size' was not an integer"

I daresay the cache is somehow corrupted, but it should not be possible to get into a state where bst can't recover

### PR DESCRIPTION
**Pull request by nanonyme**
Related to #1540

### CODE REVIEW

**Review by juergbi — APPROVED** [review]

**Comment by nanonyme** [comment]
Results in output like
```
[--:--:--][][] WARNING Failure resolving cache size

    Size '' parsed from '/var/home/nanonyme/.cache/buildstream/artifacts/cache_size' was not an integer
```
after which BuildStream continues as expected.

**Comment by nanonyme** [comment]
I converted into draft since I realized it emits the warning on every run.

**Comment by nanonyme** [comment]
@juergbi please review later again there's a reasonably major change in the flow i added to actually fix the cache.

**Review by gtristan — APPROVED** [review]
This looks safe to me.

Instead of bailing out on an invalid read of the cache size, we will end up recalculating the cache size and issuing a warning message.

**Pull request merged**
